#!/bin/bash
bspc config window_gap 0
bspc config border_width 0
bspc config split_ratio 0.62
bspc config focus_follows_pointer true
bspc config pointer_modifier mod1
bspc config automatic_shceme spiral
bspc desktop -l monocle

sxhkd &
firefox &
alacritty &
